"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";

type Agent = { id: string; name: string; role: string; status: 'active' | 'held' | 'dead'; cash: number; burn: number; colour: string; venture: string; events: string[] };
type Notice = { id: string; title: string; level: 'RED' | 'AMBER' | 'INFO'; acknowledged: boolean; time: string };
type Fleet = {
  treasury: number; contributed: number; revenue: number; spend: number; tick: number;
  agents: Agent[]; notices: Notice[];
  ledger: { id: string; label: string; amount: number; balance: number; time: string }[];
  history: number[];
  missions: { id: string; agentId: string; kind: string; brief: string; status: string; history: string[] }[];
  births: { id: string; name: string; role: string; funding: number; status: string }[];
  estates: { id: string; name: string; owner: string; size: number; assigned: string }[];
  documents: { id: string; name: string; status: string }[];
  consents: { id: string; purpose: string; active: boolean }[];
  passkeys: { id: string; name: string; active: boolean }[];
  sessions: { id: string; name: string; active: boolean }[];
  audit: string[];
  policy: { threshold: number; autoBirth: boolean; maxAgents: number; dailyHour: number; email: string; riskLimit: number; missionLimit: number };
  processed: string[];
};
type Command = { id: string; op: string; args: Record<string, string> };
const roles = ['Research', 'Marketing', 'Opportunity hunt', 'Operations', 'Communications'];
const money = (minor: number) => new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format(minor / 100);
function pence(input: string): number {
  if (!/^\d+(\.\d{1,2})?$/.test(input.trim())) throw new Error('Enter a positive amount with at most two decimal places.');
  const [whole, fraction = ''] = input.trim().split('.');
  const value = Number(whole) * 100 + Number(fraction.padEnd(2, '0'));
  if (!Number.isSafeInteger(value) || value <= 0 || value > 10000000000) throw new Error('Amount must be between £0.01 and £100,000,000.');
  return value;
}
function initialFleet(): Fleet {
  return {
    treasury: 1248200, contributed: 1000000, revenue: 432800, spend: 184600, tick: 0,
    agents: [
      { id: 'A-001', name: 'Atlas', role: 'Research', status: 'active', cash: 148200, burn: 4200, colour: 'cyan', venture: 'Signal intelligence', events: ['Research brief compiled', 'Browser: public market research', 'Evidence sources indexed'] },
      { id: 'A-002', name: 'Vega', role: 'Marketing', status: 'active', cash: 73200, burn: 3100, colour: 'violet', venture: 'Neon Studio', events: ['Campaign draft prepared', 'Business mailbox reviewed', 'Audience research completed'] },
      { id: 'A-003', name: 'Rook', role: 'Operations', status: 'active', cash: 9650, burn: 2200, colour: 'amber', venture: 'Relay Services', events: ['Runway below seven days', 'Supplier browser session completed', 'Service checklist updated'] },
      { id: 'A-004', name: 'Nova', role: 'Opportunity hunt', status: 'held', cash: 42900, burn: 1800, colour: 'green', venture: 'Frontier Labs', events: ['Owner placed agent on hold', 'Opportunity dossier saved'] },
    ],
    notices: [
      { id: 'N-1', title: 'Rook has fewer than 7 days of runway', level: 'AMBER', acknowledged: false, time: '14:32' },
      { id: 'N-2', title: 'New opportunity dossier from Nova', level: 'INFO', acknowledged: false, time: '14:18' },
    ],
    ledger: [{ id: 'L-0', label: 'Opening simulated Treasury', amount: 1248200, balance: 1248200, time: '09:00' }],
    history: [1000000, 1034200, 1018900, 1086000, 1121000, 1102300, 1184200, 1214000, 1198000, 1248200],
    missions: [{ id: 'M-001', agentId: 'A-001', kind: 'Research', brief: 'Map the demand for independent research services.', status: 'active', history: ['Assigned to Atlas', 'Initial evidence collected'] }],
    births: [],
    estates: [{ id: 'E-001', name: 'Echo research archive', owner: 'Echo (retired demo agent)', size: 128, assigned: '' }],
    documents: [{ id: 'D-001', name: 'Fictional identity card', status: 'available' }],
    consents: [{ id: 'C-001', purpose: 'Fictional provider onboarding', active: true }],
    passkeys: [{ id: 'K-001', name: 'Demo desktop authenticator', active: true }, { id: 'K-002', name: 'Demo recovery key', active: true }],
    sessions: [{ id: 'S-001', name: 'This demo browser', active: true }, { id: 'S-002', name: 'Demo tablet', active: true }],
    audit: ['14:00 · Simulated session opened'],
    policy: { threshold: 1600000, autoBirth: false, maxAgents: 12, dailyHour: 8, email: 'owner@example.invalid', riskLimit: 7, missionLimit: 3 }, processed: [],
  };
}
function evolve(current: Fleet, command: Command): Fleet {
  if (current.processed.includes(command.id)) return current;
  const s = structuredClone(current), a = command.args;
  const now = `T+${String(s.tick + 1).padStart(3, '0')}`;
  const uid = (prefix: string) => `${prefix}-${s.tick + 100}`;
  const required = (key: string) => { const value = a[key]?.trim(); if (!value) throw new Error(`${key} is required.`); return value; };
  const agent = (key = 'agentId') => { const value = s.agents.find(x => x.id === a[key]); if (!value) throw new Error('Agent not found.'); return value; };
  const living = (key = 'agentId') => { const value = agent(key); if (value.status === 'dead') throw new Error('This agent is retired.'); return value; };
  const positive = () => pence(required('amount'));
  const charge = (amount: number) => { if (amount > s.treasury) throw new Error('Insufficient Treasury balance.'); s.treasury -= amount; };
  const entry = (label: string, amount: number) => s.ledger.unshift({ id: uid('L'), label, amount, balance: s.treasury, time: now });
  const note = (title: string, level: Notice['level'] = 'INFO') => s.notices.unshift({ id: uid('N'), title, level, acknowledged: false, time: now });
  let label = '';
  switch (command.op) {
    case 'topup': { const amount = positive(); s.treasury += amount; s.contributed += amount; label = 'Treasury top-up'; entry(label, amount); break; }
    case 'withdraw': { required('reason'); const amount = positive(); charge(amount); label = 'Owner withdrawal'; entry(label, -amount); break; }
    case 'fund': { const target = living(); required('reason'); const amount = positive(); charge(amount); target.cash += amount; label = `Funded ${target.name}`; target.events.unshift(`${now} · Received ${money(amount)} from Treasury`); entry(label, -amount); break; }
    case 'transfer': { const source = living(); required('reason'); const amount = positive(); if (amount > source.cash) throw new Error('Insufficient agent balance.'); if (a.target === source.id) throw new Error('Choose a different destination.'); if (a.target === 'treasury') { s.treasury += amount; entry(`${source.name} → Treasury`, amount); } else { const target = living('target'); target.cash += amount; target.events.unshift(`${now} · Received ${money(amount)} from ${source.name}`); } source.cash -= amount; label = `${source.name} transferred ${money(amount)}`; source.events.unshift(`${now} · ${label}`); break; }
    case 'hold': { const target = living(); target.status = target.status === 'held' ? 'active' : 'held'; label = `${target.name} ${target.status === 'held' ? 'held' : 'resumed'}`; target.events.unshift(`${now} · ${label}`); break; }
    case 'role': { const target = living(); if (!roles.includes(a.role)) throw new Error('Choose a supported demo role.'); target.role = a.role; label = `${target.name} assigned ${a.role}`; target.events.unshift(`${now} · ${label}`); break; }
    case 'kill': { const target = living(); required('reason'); s.treasury += target.cash; entry(`${target.name} estate cash recovered`, target.cash); target.cash = 0; target.status = 'dead'; s.estates.push({ id: uid('E'), name: `${target.name} operational archive`, owner: target.name, size: 96, assigned: '' }); s.missions.filter(m => m.agentId === target.id && m.status === 'active').forEach(m => { m.status = 'ended'; m.history.push('Closed on agent retirement'); }); label = `${target.name} retired; estate created`; target.events.unshift(`${now} · ${label}`); break; }
    case 'mission': { const target = living(); if (s.missions.filter(m => m.agentId === target.id && m.status === 'active').length >= s.policy.missionLimit) throw new Error('Demo mission limit reached.'); const brief = required('brief'); if (!roles.includes(a.role)) throw new Error('Choose a mission kind.'); s.missions.unshift({ id: uid('M'), agentId: target.id, kind: a.role, brief, status: 'active', history: [`${now} · Assigned to ${target.name}`] }); target.events.unshift(`${now} · Mission: ${brief}`); label = `Mission assigned to ${target.name}`; break; }
    case 'mission_end': { const m = s.missions.find(x => x.id === a.missionId); if (!m || m.status !== 'active') throw new Error('Mission is no longer active.'); m.status = 'completed'; m.history.push(`${now} · ${required('outcome')}`); label = 'Mission completed'; break; }
    case 'birth': case 'reseed': { const funding = positive(); if (s.agents.filter(x => x.status !== 'dead').length + s.births.filter(x => x.status === 'queued').length >= s.policy.maxAgents) throw new Error('Demo population limit reached.'); if (!roles.includes(a.role)) throw new Error('Choose a role.'); if (command.op === 'reseed' && agent().status !== 'dead') throw new Error('Reseeding requires a retired agent.'); charge(funding); const name = required('name'); s.births.push({ id: uid('B'), name, role: a.role, funding, status: 'queued' }); label = `${name} birth queued; funds reserved`; entry(label, -funding); break; }
    case 'provision': { const birth = s.births.find(x => x.id === a.birthId); if (!birth || birth.status !== 'queued') throw new Error('Order already provisioned or missing.'); birth.status = 'provisioned'; s.agents.push({ id: uid('A'), name: birth.name, role: birth.role, status: 'active', cash: birth.funding, burn: 1500, colour: ['cyan','violet','amber','green'][s.agents.length % 4], venture: 'New venture', events: [`${now} · Simulated provisioning completed`] }); label = `${birth.name} provisioned in simulation`; break; }
    case 'estate': { const item = s.estates.find(x => x.id === a.itemId); if (!item) throw new Error('Estate item missing.'); if (a.target !== 'unassigned') living('target'); item.assigned = a.target === 'unassigned' ? '' : a.target; label = `Estate ${item.assigned ? 'assigned' : 'released'}`; break; }
    case 'ack': { const n = s.notices.find(x => x.id === a.noticeId); if (!n) throw new Error('Alert missing.'); n.acknowledged = true; label = 'Notification acknowledged'; break; }
    case 'ack_all': s.notices.forEach(n => n.acknowledged = true); label = 'All notifications acknowledged'; break;
    case 'scenario': { label = a.kind === 'RED' ? 'Simulated security incident: unrecognised sign-in refused' : a.kind === 'AMBER' ? 'Simulated spending alert: review operating costs' : 'Simulated opportunity: new qualified lead'; note(label, a.kind === 'RED' ? 'RED' : a.kind === 'AMBER' ? 'AMBER' : 'INFO'); break; }
    case 'tick': { const revenue = 12600, costs = s.agents.filter(x => x.status === 'active').reduce((sum,x) => sum+x.burn,0); charge(costs); s.treasury += revenue; s.revenue += revenue; s.spend += costs; entry('Simulated trading day: revenue less costs', revenue-costs); s.agents.filter(x => x.status === 'active').forEach(x => x.events.unshift(`${now} · ${x.role} cycle completed`)); label = 'Advanced one simulated trading day'; break; }
    case 'policy': { const threshold = pence(required('amount')); const count = Number(a.maxAgents); if (!Number.isInteger(count) || count < 1 || count > 100) throw new Error('Population limit must be 1–100.'); s.policy.threshold = threshold; s.policy.maxAgents = count; s.policy.autoBirth = a.autoBirth === 'true'; label = 'Replication policy updated'; break; }
    case 'limits': { const risk = Number(a.riskLimit), missions = Number(a.missionLimit); if (!Number.isInteger(risk) || risk < 1 || risk > 365 || !Number.isInteger(missions) || missions < 1 || missions > 20) throw new Error('Runway must be 1–365 days and mission limit 1–20.'); s.policy.riskLimit = risk; s.policy.missionLimit = missions; label = 'Risk and mission policy updated'; break; }
    case 'delivery': { const hour = Number(a.hour); if (!Number.isInteger(hour) || hour < 0 || hour > 23) throw new Error('Hour must be 0–23 UTC.'); s.policy.dailyHour = hour; s.policy.email = 'owner@example.invalid'; label = 'Demo delivery schedule updated'; break; }
    case 'genesis': s.contributed = positive(); label = 'Demo net contributed capital changed (no cash movement)'; break;
    case 'document': s.documents.push({ id: uid('D'), name: a.name === 'proof' ? 'Fictional proof of address' : 'Fictional identity card', status: 'available' }); label = 'Bundled fictional document uploaded'; break;
    case 'document_status': { const d = s.documents.find(x => x.id === a.documentId); if (!d) throw new Error('Document missing.'); d.status = d.status === 'available' ? 'revoked' : 'available'; label = `Document ${d.status}`; break; }
    case 'consent': s.consents.push({ id: uid('C'), purpose: required('purpose'), active: true }); label = 'Demo standing consent added'; break;
    case 'consent_revoke': { const c = s.consents.find(x => x.id === a.consentId); if (!c || !c.active) throw new Error('Consent already inactive.'); c.active = false; label = 'Demo consent revoked'; break; }
    case 'passkey': s.passkeys.push({ id: uid('K'), name: required('name'), active: true }); label = 'Demo passkey enrolled'; break;
    case 'passkey_revoke': { const k = s.passkeys.find(x => x.id === a.keyId); if (!k || !k.active) throw new Error('Passkey already inactive.'); if (s.passkeys.filter(x => x.active).length <= 1) throw new Error('Keep one demo passkey for recovery.'); k.active = false; label = 'Demo passkey revoked'; break; }
    case 'sessions': s.sessions.filter(x => x.id !== 'S-001').forEach(x => x.active = false); label = 'Other demo sessions revoked'; break;
    case 'totp': label = 'Demo TOTP reset completed'; break;
    case 'reveal': label = `Fictional ${a.kind === 'document' ? 'document' : 'credential'} reveal opened`; break;
    case 'login': s.sessions[0].active = true; label = 'Demo passkey + TOTP sign-in completed'; break;
    case 'logout': s.sessions[0].active = false; label = 'Demo session ended'; break;
    default: throw new Error('Unsupported simulation operation.');
  }
  s.tick += 1;
  s.processed.push(command.id);
  s.audit.unshift(`${now} · ${label}`);
  if (s.treasury !== current.treasury) s.history.push(s.treasury);
  if (!['ack','ack_all','scenario','reveal','login','logout'].includes(command.op)) note(label);
  return s;
}

interface FleetAdapter { readonly mode: 'simulation' | 'live'; snapshot(): Promise<Fleet>; execute(command: Command): Promise<Fleet>; }
class SimulationAdapter implements FleetAdapter {
  readonly mode = 'simulation' as const;
  private state = initialFleet();
  snapshot() { return Promise.resolve(structuredClone(this.state)); }
  async execute(command: Command) { this.state = evolve(this.state, command); return this.snapshot(); }
  reset() { this.state = initialFleet(); return this.snapshot(); }
}


const pages = ["Overview", "Agents", "Treasury", "Replication", "Missions", "Estates", "Owner identity", "Notifications", "Security", "Settings"];
const button = "rounded-lg border border-slate-600 px-3 py-2 text-sm hover:border-cyan-300 hover:bg-slate-800 disabled:opacity-40 focus-visible:outline-2 focus-visible:outline-cyan-300";
const input = "mt-2 w-full rounded-lg border border-slate-600 bg-slate-950 p-3 text-slate-100";
type Field = { key: string; label: string; value?: string; options?: string[][] };
type Action = { op: string; title: string; args?: Record<string, string>; fields?: Field[]; sensitive?: boolean };
type Preferences = { sound: boolean; mute: boolean; siren: boolean; volume: number; motion: boolean; large: boolean; contrast: boolean };

function Panel({ title, children }: { title: string; children: ReactNode }) {
  return <section className="rounded-xl border border-slate-700 bg-slate-900/90 p-5"><h3 className="mb-4 text-lg font-semibold">{title}</h3>{children}</section>;
}
function Soldier({ name }: { name: string }) {
  const tint = ["#67e8f9", "#c4b5fd", "#fcd34d", "#86efac"][name.charCodeAt(0) % 4];
  return <svg viewBox="0 0 32 44" className="mx-auto h-32 w-24" shapeRendering="crispEdges" role="img" aria-label={`${name}, military pixel operative`}>
    <path fill="#020617" d="M8 4h16v3h3v14h-3v4h4v12h-5v7h-8v-5h-2v5H5v-9H3V25h5z" />
    <path fill={tint} d="M9 5h14v3h3v10h-3V9H9v9H6V8h3zM7 24h18v10H7zM4 26h3v8H4zM25 26h3v8h-3z" />
    <path fill="#b5aaa0" d="M10 16h12v7H10z" /><path fill="#334155" d="M9 10h14v6H9zM10 25h12v6H10zM7 33h18v3H7z" />
    <path fill="#a7f3d0" d="M10 12h12v2H10zM12 27h3v2h-3z" /><path fill="#64748b" d="M8 36h6v5H8zM18 36h6v5h-6z" /><path fill="#172d3b" d="M6 41h9v3H6zM18 41h9v3h-9z" />
  </svg>;
}
function Chart({ values }: { values: number[] }) {
  const low = Math.min(...values) * .95, high = Math.max(...values) * 1.03;
  const points = values.map((v, i) => `${15 + i * 670 / Math.max(1, values.length - 1)},${150 - (v - low) / (high - low || 1) * 125}`).join(" ");
  return <><svg viewBox="0 0 700 180" className="w-full" role="img" aria-label="Simulated Treasury history">
    {[30, 70, 110, 150].map(y => <line key={y} x1="15" x2="685" y1={y} y2={y} stroke="#334155" />)}
    <polygon points={`15,160 ${points} 685,160`} fill="#22d3ee18" /><polyline points={points} fill="none" stroke="#67e8f9" strokeWidth="3" />
    <text x="15" y="178" fill="#94a3b8" fontSize="10">EARLIER</text><text x="645" y="178" fill="#94a3b8" fontSize="10">LATEST</text>
  </svg><p className="text-xs text-slate-400">Fictional historical samples. Real history needs a backend endpoint.</p></>;
}
function Modal({ action, close, submit }: { action: Action; close: () => void; submit: (args: Record<string, string>) => Promise<void> }) {
  const ref = useRef<HTMLDialogElement>(null), locked = useRef(false);
  const [args, setArgs] = useState<Record<string, string>>({ ...action.args, ...Object.fromEntries((action.fields || []).map(f => [f.key, f.value ?? f.options?.[0]?.[0] ?? ""])) });
  const [review, setReview] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  useEffect(() => { const el = ref.current; el?.showModal(); return () => el?.close(); }, []);
  return <dialog ref={ref} onCancel={e => { if (busy) e.preventDefault(); else close(); }} className="fixed inset-0 m-auto max-h-[90vh] w-[min(92vw,520px)] overflow-y-auto rounded-2xl border border-cyan-700 bg-slate-900 p-6 text-white backdrop:bg-black/80">
    <form onSubmit={async e => { e.preventDefault(); if (locked.current) return; if (!review) { setReview(true); return; } locked.current = true; setBusy(true); setError(""); try { await submit(args); close(); } catch (e) { setError(e instanceof Error ? e.message : "Operation failed"); } finally { locked.current = false; setBusy(false); } }}>
      <p className="text-xs tracking-widest text-amber-300">SIMULATION ONLY</p><h2 className="my-3 text-2xl">{action.title}</h2>
      {!review ? (action.fields || []).map(f => <label key={f.key} className="my-4 block text-sm">{f.label}{f.options ? <select className={input} value={args[f.key]} onChange={e => setArgs({ ...args, [f.key]: e.target.value })}>{f.options.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select> : <input className={input} required autoComplete="off" maxLength={180} value={args[f.key]} onChange={e => setArgs({ ...args, [f.key]: e.target.value })} />}</label>) : <><p className="text-sm text-slate-300">Review these changes to fictional Fleet data.</p><dl className="my-4 space-y-2">{Object.entries(args).map(([k, v]) => <div key={k} className="flex justify-between gap-4 break-all text-sm"><dt className="text-slate-400">{k}</dt><dd>{v}</dd></div>)}</dl>{action.sensitive && <p className="rounded bg-amber-950 p-3 text-sm text-amber-200">Confirming simulates a fresh owner authentication check. No real passkey or funds are used.</p>}</>}
      {error && <p role="alert" className="my-3 text-red-300">{error}</p>}<div className="mt-6 flex flex-wrap gap-2"><button type="button" className={button} disabled={busy} onClick={close}>Cancel</button>{review && <button type="button" className={button} disabled={busy} onClick={() => setReview(false)}>Edit</button>}<button className={`${button} bg-cyan-900`} disabled={busy}>{busy ? "Applying…" : review ? "Confirm simulation" : "Review changes"}</button></div>
    </form></dialog>;
}
function Reveal({ kind, close }: { kind: string; close: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const el = ref.current; el?.showModal(); const timer = setTimeout(close, 60000); return () => { clearTimeout(timer); el?.close(); }; }, [close]);
  return <dialog ref={ref} onCancel={close} className="fixed inset-0 m-auto w-[min(92vw,520px)] rounded-xl border border-cyan-700 bg-slate-900 p-6 text-white backdrop:bg-black/80"><p className="text-xs text-amber-300">FICTIONAL SAMPLE · CLOSES AFTER 60 SECONDS</p><h2 className="my-4 text-xl">{kind === "document" ? "Training identity card" : "Demo credential"}</h2><div className="my-5 rounded border border-dashed border-cyan-500 bg-slate-950 p-6 font-mono">{kind === "document" ? <>ALEX EXAMPLE<br />000 DEMO STREET<br />FICTIONAL-0000<br /><br />NOT A VALID IDENTITY DOCUMENT</> : "DEMO-ONLY-NOT-A-REAL-KEY-0000"}</div><p className="mb-4 text-sm text-slate-400">This sample is not encrypted. Live reveals require the verified broker implementation.</p><button className={button} onClick={close}>Close and clear</button></dialog>;
}

export default function Home() {
  const [adapter] = useState(() => new SimulationAdapter());
  const [fleet, setFleet] = useState(initialFleet), [page, setPage] = useState("Overview"), [mode, setMode] = useState("Dashboard"), [agentId, setAgentId] = useState("");
  const [action, setAction] = useState<Action | null>(null), [reveal, setReveal] = useState("");
  const [query, setQuery] = useState(""), [filter, setFilter] = useState("all"), [sort, setSort] = useState("name"), [noticeFilter, setNoticeFilter] = useState("all"), [estateQuery, setEstateQuery] = useState("");
  const [feedback, setFeedback] = useState("Simulation ready. All names and balances are fictional."), [fault, setFault] = useState("none"), [loginStage, setLoginStage] = useState(0), [code, setCode] = useState("");
  const [prefs, setPrefs] = useState<Preferences>({ sound: false, mute: false, siren: false, volume: 30, motion: true, large: false, contrast: false });
  const audio = useRef<AudioContext | null>(null), lastSiren = useRef(0), heard = useRef(new Set<string>());
  const selected = fleet.agents.find(a => a.id === agentId), alive = fleet.agents.filter(a => a.status !== "dead");
  const active = alive.filter(a => a.status === "active"), unread = fleet.notices.filter(n => !n.acknowledged);
  const roleOptions = roles.map(r => [r, r]);
  const agentOptions = alive.map(a => [a.id, a.name]);
  const amount: Field = { key: "amount", label: "Amount in GBP", value: "100.00" };
  const reason: Field = { key: "reason", label: "Reason", value: "Owner simulation exercise" };
  const chooseAgent: Field = { key: "agentId", label: "Agent", options: agentOptions };
  const chooseRole: Field = { key: "role", label: "Assignment", options: roleOptions };
  useEffect(() => {
    const sync = () => { const [p, a] = decodeURIComponent(location.hash.slice(1)).split("/"); if (p === "Virtual") { setMode("Virtual"); setAgentId(a || ""); } else { setMode("Dashboard"); setPage(pages.includes(p) ? p : "Overview"); setAgentId(a || ""); } };
    const timer = setTimeout(sync, 0); window.addEventListener("hashchange", sync); window.addEventListener("popstate", sync);
    return () => { clearTimeout(timer); window.removeEventListener("hashchange", sync); window.removeEventListener("popstate", sync); };
  }, []);
  useEffect(() => () => { void audio.current?.close(); }, []);
  function go(p: string, id = "") { setMode(p === "Virtual" ? "Virtual" : "Dashboard"); if (p !== "Virtual") setPage(p); setAgentId(id); window.history.pushState(null, "", "#" + encodeURIComponent(p + (id ? "/" + id : ""))); }
  function tone(urgent = false) {
    if (!prefs.sound || prefs.mute || (urgent && !prefs.siren)) return;
    if (urgent && Date.now() - lastSiren.current < 10000) return;
    if (urgent) lastSiren.current = Date.now();
    try { const context = audio.current || new AudioContext(); audio.current = context; void context.resume(); const oscillator = context.createOscillator(), gain = context.createGain(); oscillator.connect(gain); gain.connect(context.destination); const t = context.currentTime; oscillator.frequency.setValueAtTime(urgent ? 660 : 440, t); oscillator.frequency.linearRampToValueAtTime(urgent ? 990 : 580, t + .18); gain.gain.setValueAtTime(prefs.volume / 100 * .12, t); gain.gain.exponentialRampToValueAtTime(.001, t + (urgent ? .8 : .15)); oscillator.start(); oscillator.stop(t + (urgent ? .85 : .2)); } catch { setFeedback("Audio is unavailable in this browser."); }
  }
  async function run(op: string, args: Record<string, string> = {}) {
    if (fault !== "none") throw new Error(`Simulated ${fault}. Clear the scenario in Settings to retry.`);
    await new Promise(resolve => setTimeout(resolve, 180));
    const next = await adapter.execute({ id: crypto.randomUUID(), op, args }); setFleet(next); setFeedback(next.audit[0]);
    for (const n of next.notices) if (n.level === "RED" && !n.acknowledged && !heard.current.has(n.id)) { heard.current.add(n.id); tone(true); }
    return next;
  }
  function open(op: string, title: string, fields: Field[] = [], args: Record<string, string> = {}, sensitive = false) { setAction({ op, title, fields, args, sensitive }); }
  function control(label: string, op: string, fields: Field[] = [], args: Record<string, string> = {}, sensitive = false) { return <button className={button} onClick={() => open(op, label, fields, args, sensitive)}>{label}</button>; }
  function notices() { return <div className="space-y-3">{unread.length === 0 && <p className="text-slate-400">No unacknowledged simulated alerts.</p>}{fleet.notices.filter(n => noticeFilter === "all" || n.level === noticeFilter || (noticeFilter === "unread" && !n.acknowledged)).slice(0, page === "Overview" ? 4 : 50).map(n => <div key={n.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-700 p-3"><div><span className={n.level === "RED" ? "text-red-300" : n.level === "AMBER" ? "text-amber-300" : "text-cyan-300"}>{n.level}</span><p className="my-1 text-sm">{n.title}</p><small className="text-slate-400">{n.time} · {n.acknowledged ? "Acknowledged" : "Unread"}</small></div>{!n.acknowledged && control("Acknowledge", "ack", [], { noticeId: n.id })}</div>)}</div>; }
  function listAgents() {
    const results = fleet.agents.filter(a => (a.name + a.role).toLowerCase().includes(query.toLowerCase()) && (filter === "all" || a.status === filter)).sort((a, b) => sort === "cash" ? b.cash - a.cash : a.name.localeCompare(b.name));
    return <><div className="mb-4 grid gap-3 sm:grid-cols-3"><label className="text-sm">Search agents<input className={input} value={query} onChange={e => setQuery(e.target.value)} placeholder="Name or assignment" /></label><label className="text-sm">Status<select className={input} value={filter} onChange={e => setFilter(e.target.value)}>{["all", "active", "held", "dead"].map(x => <option key={x}>{x}</option>)}</select></label><label className="text-sm">Sort<select className={input} value={sort} onChange={e => setSort(e.target.value)}><option value="name">Name</option><option value="cash">Wallet, highest first</option></select></label></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-600 text-slate-400"><tr>{["Agent", "Assignment", "Status", "Wallet", "Runway"].map(x => <th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{results.map(a => <tr key={a.id} className="border-b border-slate-800"><td className="p-3"><button className="text-cyan-300 underline" onClick={() => go("Agents", a.id)}>{a.name}</button><small className="block text-slate-500">{a.id}</small></td><td className="p-3">{a.role}</td><td className="p-3">{a.status}</td><td className="p-3 font-mono">{money(a.cash)}</td><td className="p-3">{Math.floor(a.cash / a.burn)} days</td></tr>)}</tbody></table>{!results.length && <p className="py-6">No matching agents.</p>}</div></>;
  }
  function profile(a: Agent) { return <div className="space-y-5"><button className={button} onClick={() => go(mode === "Virtual" ? "Virtual" : "Agents")}>← Close profile</button><Panel title={`${a.name} / ${a.id}`}><div className="grid gap-6 sm:grid-cols-[120px_1fr]"><Soldier name={a.name} /><div><p className="text-cyan-300">{a.role} · {a.status.toUpperCase()}</p><p className="my-3 text-3xl font-mono">{money(a.cash)}</p><p className="text-slate-400">{a.venture} · Fictional operative</p></div></div><div className="mt-5 flex flex-wrap gap-2">{a.status !== "dead" ? <>{control(a.status === "held" ? "Resume" : "Hold", "hold", [], { agentId: a.id })}{control("Assign role", "role", [chooseRole], { agentId: a.id })}{control("Fund agent", "fund", [amount, reason], { agentId: a.id }, true)}{control("Transfer", "transfer", [amount, { key: "target", label: "Destination", options: [["treasury", "Treasury"], ...agentOptions.filter(([id]) => id !== a.id)] }, reason], { agentId: a.id }, true)}{control("Assign mission", "mission", [chooseRole, { key: "brief", label: "Mission brief" }], { agentId: a.id })}{control("Retire agent", "kill", [reason], { agentId: a.id }, true)}</> : control("Reseed", "reseed", [{ key: "name", label: "New agent name", value: a.name + " II" }, chooseRole, amount], { agentId: a.id }, true)}</div></Panel><Panel title="Economics & exposure"><p>Daily burn: {money(a.burn)} · Runway: {Math.floor(a.cash / a.burn)} days</p><p className="mt-3 text-amber-200">{a.cash / a.burn < fleet.policy.riskLimit ? "Below configured runway threshold" : "Above configured runway threshold"}</p><p className="mt-3 text-sm text-slate-400">Demo cash-based runway. Real commitments and exposure require the risk response.</p></Panel><Panel title="Venture & sales"><p>{a.venture}</p><p className="mt-2 text-sm text-slate-400">Fictional venture relationship. Customer records and per-agent sales need backend models.</p><details className="mt-3"><summary className="cursor-pointer text-cyan-300">Demo sales record</summary><p className="mt-3">Example Customer · Research brief · £120 · Fictional completed sale</p></details></Panel><Panel title="Activity & browser"><ol className="space-y-3">{a.events.map((e, i) => <li key={i} className="border-l-2 border-cyan-800 pl-3 text-sm">{e}</li>)}</ol><p className="mt-4 text-xs text-slate-400">Illustrative event history; no live browser session is connected.</p></Panel><Panel title="Credential inventory"><p className="mb-4">Demo service key · example.invalid · value hidden</p>{control("Reveal fictional credential", "reveal", [], { kind: "credential" }, true)}</Panel></div>; }
  const signedIn = fleet.sessions[0].active;
  return <main className={`${prefs.contrast ? "bg-black text-white" : "bg-slate-950 text-slate-100"} min-h-screen w-full ${prefs.large ? "text-lg" : "text-base"}`}>
    <div className="border-b border-amber-800 bg-amber-950/60 px-5 py-2 text-center text-xs tracking-widest text-amber-200">SIMULATION · FICTIONAL DATA · NO MACHINE OR REAL MONEY CONNECTED</div>
    <div className="mx-auto grid max-w-screen-2xl lg:min-h-screen lg:grid-cols-[220px_1fr]">
      <aside className="border-b border-slate-800 bg-slate-900/60 p-5 lg:border-r"><p className="text-xs tracking-[.25em] text-cyan-300">AUTOMATON FLEET</p><h1 className="mt-2 text-xl font-bold">Command Deck</h1><p className="mt-1 text-xs text-slate-500">OWNER OPERATIONS / 01</p><nav aria-label="Main navigation" className="mt-6 flex gap-2 overflow-x-auto lg:flex-col">{pages.map((p, i) => <button key={p} disabled={!signedIn} aria-current={page === p && mode === "Dashboard" ? "page" : undefined} onClick={() => go(p)} className={`shrink-0 rounded-lg px-3 py-3 text-left text-sm ${page === p && mode === "Dashboard" ? "bg-cyan-950 text-cyan-200" : "text-slate-400 hover:bg-slate-800"}`}><span className="mr-3 font-mono text-xs opacity-50">{String(i + 1).padStart(2, "0")}</span>{p}{p === "Notifications" && ` (${unread.length})`}</button>)}</nav><p className="mt-8 text-xs text-slate-500">Local simulation<br />Changes reset on refresh</p></aside>
      <div className="min-w-0 p-5 sm:p-8"><header className="mb-6 flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 pb-5"><div><p className="text-xs tracking-widest text-slate-400">FLEET CONTROL CENTRE</p><h2 className="mt-2 text-3xl font-semibold">{selected ? selected.name : mode === "Virtual" ? "Virtual headquarters" : page}</h2></div><div className="flex flex-wrap gap-2">{["Dashboard", "Virtual"].map(m => <button key={m} className={`${button} ${mode === m ? "bg-cyan-900 text-cyan-100" : ""}`} disabled={!signedIn} aria-pressed={mode === m} onClick={() => go(m === "Virtual" ? "Virtual" : "Overview")}>{m}</button>)}<button className={button} onClick={() => setPrefs({ ...prefs, mute: !prefs.mute })}>{prefs.mute ? "Unmute" : "Mute"}</button></div></header>
      <p role="status" className="mb-5 rounded border border-slate-700 px-4 py-3 text-sm text-cyan-200">{feedback}</p>
      {fault !== "none" && <p role="alert" className="mb-5 rounded bg-red-950 p-4 text-red-200">Scenario: {fault}. Displayed data is stale. Open Settings to recover.</p>}
      {!signedIn ? <Panel title="Simulated sign-in"><p className="mb-4 text-amber-200">Training flow only. No real authentication takes place.</p>{loginStage === 0 ? <button className={button} onClick={() => setLoginStage(1)}>Simulate passkey verification</button> : <form onSubmit={async e => { e.preventDefault(); if (code !== "123456") { setFeedback("Use the displayed training code 123456."); return; } try { await run("login"); setLoginStage(0); setCode(""); } catch (e) { setFeedback(String(e)); } }}><label>Training TOTP code: 123456<input className={input} inputMode="numeric" value={code} onChange={e => setCode(e.target.value)} /></label><button className={`${button} mt-4`}>Complete simulated sign-in</button></form>}</Panel> : selected ? profile(selected) : mode === "Virtual" ? <section><div className="mb-4 flex flex-wrap justify-between gap-3"><p className="text-sm text-cyan-300">OPERATIONS FLOOR / ILLUSTRATIVE ACTIVITY</p><span className="text-xs text-slate-400">Select a workstation to inspect its operative</span></div><div className="rounded-2xl border-4 border-slate-700 bg-[repeating-linear-gradient(0deg,#0f172a_0px,#0f172a_39px,#243040_40px)] p-5 sm:p-10"><div className="mb-8 flex justify-between border-b-4 border-slate-600 pb-5 font-mono text-xs text-cyan-300"><span>RESEARCH // COMMS</span><span>CENTRAL COMMAND</span><span>VENTURES // OPS</span></div><div className="grid gap-x-10 gap-y-12 sm:grid-cols-2 xl:grid-cols-3">{alive.map(a => <button key={a.id} className="group rounded-lg border border-slate-600 bg-slate-950/90 p-4 text-left hover:border-cyan-300 focus-visible:outline-2 focus-visible:outline-cyan-300" onClick={() => go("Virtual", a.id)}><div className="mb-4 rounded border-4 border-slate-600 bg-cyan-950 p-3 font-mono text-xs text-cyan-200"><p>{a.role.toUpperCase()}</p><p className={prefs.motion && a.status === "active" ? "mt-2 animate-pulse motion-reduce:animate-none" : "mt-2"}>{a.status === "active" ? "▰ ▰ ▰ ▱  DEMO CYCLE" : "▱ ▱ ▱ ▱  ON HOLD"}</p></div><Soldier name={a.name} /><div className="mt-3 flex items-center justify-between gap-2"><strong>{a.name}</strong><span className="font-mono text-cyan-300">{money(a.cash)}</span></div><p className="mt-2 text-xs text-slate-400">{a.status} · {a.events[0]}</p></button>)}</div><div className="mt-10 border-t-4 border-dashed border-slate-600 pt-4 text-center font-mono text-xs tracking-[.3em] text-slate-500">ACCESS CORRIDOR // FLEET HQ</div></div></section> : <div className="space-y-5">
      {page === "Overview" && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Treasury", money(fleet.treasury), "Treasury"], ["Net profit · demo period", money(fleet.revenue - fleet.spend), "Treasury"], ["Active agents", `${active.length} / ${alive.length}`, "Agents"], ["Health findings", `${unread.filter(n => n.level !== "INFO").length} open`, "Notifications"]].map(([label, value, destination]) => <button key={label} onClick={() => go(destination)} className="rounded-xl border border-slate-700 bg-slate-900 p-5 text-left hover:border-cyan-500"><p className="text-sm text-slate-400">{label}</p><p className="mt-4 font-mono text-3xl text-cyan-200">{value}</p><p className="mt-3 text-xs text-slate-500">Inspect breakdown →</p></button>)}</div><div className="grid gap-5 xl:grid-cols-[1.6fr_1fr]"><Panel title="Treasury trajectory"><Chart values={fleet.history} /></Panel><Panel title="Operational readiness"><svg viewBox="0 0 180 105" className="mx-auto h-32" role="img" aria-label={`${active.length} of ${alive.length} living agents active`}><path d="M20 90 A70 70 0 0 1 160 90" fill="none" stroke="#334155" strokeWidth="12" /><path d="M20 90 A70 70 0 0 1 160 90" fill="none" stroke="#67e8f9" strokeWidth="12" pathLength="100" strokeDasharray={`${alive.length ? active.length / alive.length * 100 : 0} 100`} /><text x="90" y="80" textAnchor="middle" fill="#e2e8f0" fontSize="26">{active.length}/{alive.length}</text></svg><p className="text-center text-sm text-slate-400">Active / living agents</p></Panel></div><Panel title="Priority feed">{notices()}</Panel><Panel title="Agent operations">{listAgents()}</Panel></>}
      {page === "Agents" && <Panel title="Agent registry">{listAgents()}</Panel>}
      {page === "Treasury" && <><Panel title="Treasury control"><p className="font-mono text-4xl text-cyan-200">{money(fleet.treasury)}</p><div className="my-5 flex flex-wrap gap-2">{control("Top up", "topup", [amount], {}, true)}{control("Withdraw", "withdraw", [amount, reason], {}, true)}{control("Fund agent", "fund", [chooseAgent, amount, reason], {}, true)}{control("Net contributed capital", "genesis", [{ ...amount, value: String(fleet.contributed / 100) }], {}, true)}</div><p className="text-sm text-slate-400">Demo revenue {money(fleet.revenue)} · costs {money(fleet.spend)} · profit {money(fleet.revenue - fleet.spend)}</p><p className="mt-3 text-sm text-slate-400">Net contributed capital {money(fleet.contributed)}. Changing it does not deposit cash. Live top-up requires a deposit/reconciliation contract.</p><Chart values={fleet.history} /></Panel><Panel title="Transaction history"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Time", "Transaction", "Movement", "Treasury after"].map(x => <th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{fleet.ledger.map(l => <tr key={l.id} className="border-t border-slate-700"><td className="p-3">{l.time}</td><td className="p-3">{l.label}</td><td className="p-3 font-mono">{money(l.amount)}</td><td className="p-3 font-mono">{money(l.balance)}</td></tr>)}</tbody></table></div></Panel></>}
      {page === "Replication" && <><Panel title="Replication ladder"><p className="text-2xl">Next threshold: {money(fleet.policy.threshold)}</p><progress className="my-5 h-4 w-full accent-cyan-400" max={fleet.policy.threshold} value={Math.max(0, fleet.treasury - fleet.contributed)} /><p>Illustrative wealth: {money(Math.max(0, fleet.treasury - fleet.contributed))}</p><p className="my-3 text-sm text-slate-400">Wealth definition awaits owner confirmation. Health window: not started. Live birth provisioning is unfinished.</p><div className="flex flex-wrap gap-2">{control("Queue birth", "birth", [{ key: "name", label: "Agent name" }, chooseRole, amount], {}, true)}{control("Replication policy", "policy", [{ ...amount, label: "Wealth threshold (GBP)", value: String(fleet.policy.threshold / 100) }, { key: "maxAgents", label: "Maximum agents", value: String(fleet.policy.maxAgents) }, { key: "autoBirth", label: "Automatic policy preference (no background provisioning)", options: [["false", "Off"], ["true", "On — preference only"]] }], {}, true)}</div></Panel><Panel title="Birth orders">{fleet.births.length === 0 && <p>No orders. Queue a fictional birth to test the lifecycle.</p>}{fleet.births.map(b => <div key={b.id} className="flex flex-wrap justify-between gap-3 border-b border-slate-700 py-4"><div><strong>{b.name}</strong><p className="text-sm text-slate-400">{b.role} · {money(b.funding)} reserved · {b.status}</p></div>{b.status === "queued" && control("Simulate provisioning", "provision", [], { birthId: b.id }, true)}</div>)}</Panel></>}
      {page === "Missions" && <><div className="flex flex-wrap gap-2">{control("Create mission", "mission", [chooseAgent, chooseRole, { key: "brief", label: "Mission brief" }])}{control("Mission & risk limits", "limits", [{ key: "riskLimit", label: "Runway warning (days)", value: String(fleet.policy.riskLimit) }, { key: "missionLimit", label: "Active missions per agent", value: String(fleet.policy.missionLimit) }], {}, true)}</div>{fleet.missions.map(m => <Panel key={m.id} title={`${m.kind} / ${m.status}`}><p>{m.brief}</p><p className="my-3 text-sm text-cyan-300">Assigned to {fleet.agents.find(a => a.id === m.agentId)?.name}</p><details className="mb-4"><summary className="cursor-pointer">Review history</summary>{m.history.map((h, i) => <p className="mt-2 text-sm text-slate-400" key={i}>{h}</p>)}</details>{m.status === "active" && control("Complete mission", "mission_end", [{ key: "outcome", label: "Outcome" }], { missionId: m.id })}</Panel>)}</>}
      {page === "Estates" && <Panel title="Estate inventory"><p>{fleet.estates.reduce((sum, e) => sum + e.size, 0)} MB / 1,024 MB demo storage</p><progress className="my-3 w-full accent-cyan-400" max={1024} value={fleet.estates.reduce((sum, e) => sum + e.size, 0)} /><label className="text-sm">Filter items<input className={input} value={estateQuery} onChange={e => setEstateQuery(e.target.value)} /></label>{fleet.estates.filter(e => e.name.toLowerCase().includes(estateQuery.toLowerCase())).map(e => <div key={e.id} className="border-b border-slate-700 py-4"><h4>{e.name}</h4><p className="my-2 text-sm text-slate-400">{e.size} MB · {e.assigned ? fleet.agents.find(a => a.id === e.assigned)?.name : "Unassigned"}</p>{control("Assign / release", "estate", [{ key: "target", label: "Assign to", options: [["unassigned", "Release assignment"], ...agentOptions] }], { itemId: e.id }, true)}</div>)}<p className="mt-4 text-xs text-slate-400">Storage is simulated. Physical archive compression is not implemented in the reported backend.</p></Panel>}
      {page === "Owner identity" && <><Panel title="Fictional document vault"><p className="mb-4 text-amber-200">Training samples only. Do not enter real personal information.</p>{control("Upload bundled sample", "document", [{ key: "name", label: "Fictional sample", options: [["identity", "Training identity card"], ["proof", "Training proof of address"]] }], {}, true)}{fleet.documents.map(d => <div key={d.id} className="mt-4 rounded border border-slate-700 p-4"><p>{d.name} · {d.status}</p><div className="mt-3 flex flex-wrap gap-2">{d.status === "available" && control("Preview sample", "reveal", [], { kind: "document" }, true)}{control(d.status === "available" ? "Revoke" : "Restore", "document_status", [], { documentId: d.id }, true)}</div></div>)}</Panel><Panel title="Standing consents">{control("Add demo consent", "consent", [{ key: "purpose", label: "Fictional purpose", value: "Example provider onboarding" }], {}, true)}{fleet.consents.map(c => <div key={c.id} className="mt-4 flex flex-wrap justify-between gap-3"><p>{c.purpose} · {c.active ? "active" : "revoked"}</p>{c.active && control("Revoke consent", "consent_revoke", [], { consentId: c.id }, true)}</div>)}</Panel></>}
      {page === "Notifications" && <><Panel title="Notification controls"><label>Filter<select className={input} value={noticeFilter} onChange={e => setNoticeFilter(e.target.value)}>{["all", "unread", "RED", "AMBER", "INFO"].map(n => <option key={n}>{n}</option>)}</select></label><div className="mt-4 flex flex-wrap gap-2">{control("Acknowledge all", "ack_all")}{control("Delivery policy", "delivery", [{ key: "hour", label: "Daily report hour (UTC)", value: String(fleet.policy.dailyHour) }], {}, true)}</div><p className="mt-3 text-xs text-slate-400">Demo recipient: {fleet.policy.email} · {fleet.policy.dailyHour}:00 UTC · No email sent</p></Panel><Panel title="Alert feed">{notices()}</Panel></>}
      {page === "Security" && <><Panel title="Authentication simulation"><p className="mb-4 text-amber-200">No real passkeys, TOTP secrets or authentication are used here.</p><div className="flex flex-wrap gap-2">{control("Enroll demo passkey", "passkey", [{ key: "name", label: "Demo authenticator name" }], {}, true)}{control("Reset demo TOTP", "totp", [], {}, true)}{control("Sign out elsewhere", "sessions", [], {}, true)}{control("Sign out of demo", "logout")}</div>{fleet.passkeys.map(k => <div key={k.id} className="mt-4 flex flex-wrap justify-between gap-3"><p>{k.name} · {k.active ? "active" : "revoked"}</p>{k.active && control("Revoke key", "passkey_revoke", [], { keyId: k.id }, true)}</div>)}<h4 className="mt-5 font-semibold">Sessions</h4>{fleet.sessions.map(s => <p key={s.id} className="mt-2 text-sm text-slate-400">{s.name}: {s.active ? "active" : "signed out"}</p>)}</Panel><Panel title="Audit & reveal log"><ol className="max-h-96 space-y-3 overflow-y-auto text-sm">{fleet.audit.map((e, i) => <li key={i} className="border-l-2 border-slate-600 pl-3">{e}</li>)}</ol></Panel></>}
      {page === "Settings" && <><Panel title="Sound & accessibility"><div className="grid gap-4 sm:grid-cols-2">{([["sound", "Enable sound"], ["mute", "Mute all audio"], ["siren", "Urgent alert siren"], ["motion", "Animate workstations"], ["large", "Larger text"], ["contrast", "High contrast"]] as const).map(([key, label]) => <label key={key} className="flex items-center gap-3"><input type="checkbox" checked={prefs[key]} onChange={e => setPrefs({ ...prefs, [key]: e.target.checked })} />{label}</label>)}</div><label className="mt-5 block">Volume: {prefs.volume}%<input aria-label="Audio volume" type="range" min="0" max="100" value={prefs.volume} onChange={e => setPrefs({ ...prefs, volume: Number(e.target.value) })} className="mt-3 w-full" /></label><button className={button} onClick={() => tone(false)}>Test sound</button><p className="mt-4 text-sm text-slate-400">Sound requires enablement. Sirens play once for each new urgent alert, with a ten-second cooldown. System reduced-motion settings are respected.</p></Panel><Panel title="Reproducible scenarios"><div className="flex flex-wrap gap-2">{control("Advance trading day", "tick")}{control("Urgent security event", "scenario", [], { kind: "RED" })}{control("Spending warning", "scenario", [], { kind: "AMBER" })}{control("New opportunity", "scenario", [], { kind: "INFO" })}<button className={button} onClick={() => open("reset", "Reset all fictional data", [], {}, true)}>Reset simulation</button></div><label className="mt-5 block">Connection/error scenario<select className={input} value={fault} onChange={e => setFault(e.target.value)}>{["none", "disconnected", "session expired", "forbidden", "rate-limited", "server failure"].map(f => <option key={f}>{f}</option>)}</select></label><p className="mt-4 text-sm text-slate-400">Choose “none” to recover. Failed actions never change simulated balances.</p></Panel><Panel title="Integration status"><p className="text-amber-200">Live integration pending.</p><p className="mt-3 text-sm text-slate-400">Existing same-origin gateway, authentication, sealed reveals and response schemas need verification against backend source. Production mutations are disabled. Treasury top-up, persistent roles, historical charts, customer models and live birth provisioning need confirmed contracts.</p></Panel></>}
      </div>}
      </div>
    </div>
    {action && <Modal key={action.op + action.title} action={action} close={() => setAction(null)} submit={async args => { if (action.op === "reset") { setFleet(await adapter.reset()); setFault("none"); setAgentId(""); heard.current.clear(); setFeedback("Simulation reset to the original fixture."); return; } await run(action.op, args); if (action.op === "reveal") setReveal(args.kind); }} />}
    {reveal && <Reveal kind={reveal} close={() => setReveal("")} />}
  </main>;
}



